export const WS_SOCKET_OPEN = 'WS_SOCKET_OPEN';
export const WS_SOCKET_OPEN_PRIVATE = 'WS_SOCKET_OPEN_PRIVATE';
export const WS_SOCKET_CLOSE = 'WS_SOCKET_CLOSE';
export const WS_OPEN_SUCCESS = 'WS_OPEN_SUCCESS';
export const WS_CLOSE_SUCCESS = 'WS_CLOSE_SUCCESS';
export const WS_SOCKET_ERROR = 'WS_SOCKET_ERROR';
export const WS_SOCKET_ONMESSAGE = 'WS_SOCKET_ONMESSAGE';
export const WS_SOCKET_ONMESSAGE_PRIVATE = 'WS_SOCKET_ONMESSAGE_PRIVATE';
